--ATENDENTES
INSERT INTO ATENDENTES (no_atendente) VALUES ('RENATO');
INSERT INTO ATENDENTES (no_atendente) VALUES ('BRUNO');
INSERT INTO ATENDENTES (no_atendente) VALUES ('THIAGO');
INSERT INTO ATENDENTES (no_atendente) VALUES ('PEDRO');
INSERT INTO ATENDENTES (no_atendente) VALUES ('MATEUS');
INSERT INTO ATENDENTES (no_atendente) VALUES ('ROSA');
INSERT INTO ATENDENTES (no_atendente) VALUES ('FERNANDA');
INSERT INTO ATENDENTES (no_atendente) VALUES ('TALITA');
INSERT INTO ATENDENTES (no_atendente) VALUES ('ELEN');
INSERT INTO ATENDENTES (no_atendente) VALUES ('JULIA');
INSERT INTO ATENDENTES (no_atendente) VALUES ('BIANCA');
INSERT INTO ATENDENTES (no_atendente) VALUES ('PEDRO');

--TIMES
INSERT INTO TIMES (en_time_setor) VALUES ('CARTAO');
INSERT INTO TIMES (en_time_setor) VALUES ('EMPRESTIMO');
INSERT INTO TIMES (en_time_setor) VALUES ('OUTROS');
